#!/bin/bash

help() {
    echo "App"
    echo "========================="
    echo "start     Run the application"
    echo "test      Test the application"
}

# Setup Tab Complete
_tab_complete() {
    local cur prev opts
    opts="start test"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _tab_complete run

cmd=$1

# Remove the first argument (shift left)
shift

case $cmd in
    "start")
        echo "TODO: Add [start]"
        # Use "$@" to pass all remaining arguments.
        ;;
    "test")
        echo "TODO: Add [test]"
        # Use "$@" to pass all remaining arguments.
        ;;
    *)
        help
        ;;
esac