site_name: Joel Vandiver
repo_url: https://github.com/joelvandiver/joelvandiver.com
repo_name: joelvandiver.com
# nav:
#   - Blog:
#     - blog/index.md
    # - blog/authors.md
plugins:
  # ref:  https://squidfunk.github.io/mkdocs-material/plugins/blog/
  - blog:
      blog_dir: blog
      blog_toc: true
      draft: true
      pagination_per_page: 10
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      categories: true
      categories_name: Categories
      archive: true
  - search
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.select
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
extra_javascript:
  - scripts/site.js
#   - scripts/feedback.js
extra_css:
  - styles/site.css
extra:
  analytics:
    provider: google
    property: G-QL8GEFVL1T
    feedback:
      title: Feedback
      ratings:
          - icon: material/thumb-up-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/thumb-down-outline
            name: This page could be improved
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="..." target="_blank" rel="noopener">feedback form</a>.