site_name: Joel Vandiver
# nav:
#   - Home: index.md
#   - About: about.md
theme:
  name: material
  # custom_dir: docs/overrides
  favicon: images/favicon.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode